### PR TITLE
Unit-test LUBs.

### PR DESCRIPTION
**Pull request by folone**
Here are some unit tests. @adriaanm is this something you had in mind for this?

### CODE REVIEW

**Comment by adriaanm** [comment]
Thanks, @folone! I'll have a look tomorrow. Just moved back to SF ;-)

**Comment by folone** [comment]
Oh, get un jet lagged first then!

**Comment by adriaanm** [comment]
Thanks! Good start! I added some comments over at 8ae5c19051b81c7976d81c003c15180bc42b01c3.
Would be good to have one test method for each category ("category" as suggested in the other comment).

**Comment by milessabin** [comment]
@folone any chance you could rebase against https://github.com/milessabin/scala/commits/topic/sip-23-redux and send those tests my way as a PR?

**Comment by folone** [comment]
@milessabin will do tonight!

**Pull request closed without merging**
